INSERT INTO EXERCISE values (1, 'TESTE', 30, 3, 30);
INSERT INTO EXERCISE values (2, 'TESTE UPDATE', 40, 2, 50);
INSERT INTO EXERCISE values (3, 'TESTE DELETE', 50, 2, 100);

INSERT INTO ACTIVITY VALUES (1, 'TESTE ACTIVITY', 0);
INSERT INTO ACTIVITY VALUES (2, 'TESTE ACTIVITY EXERCISE', 0);
INSERT INTO ACTIVITY VALUES (3, 'TESTE ACTIVITY DELETE', 0);
INSERT INTO ACTIVITY VALUES (4, 'TESTE ACTIVITY EXERCISE DELETE', 0);

INSERT INTO ACTIVITY_EXERCISE VALUES (2, 1);
INSERT INTO ACTIVITY_EXERCISE VALUES (4, 1);